import {
  Account,
  CreditCard,
  Transaction,
  RecurringTransaction,
  Subscription,
  Budget,
  Loan,
  Investment,
  DebtRecord,
  Merchant,
  Goal,
} from '../types';

export function getDemoData(): {
  accounts: Account[];
  creditCards: CreditCard[];
  merchants: Merchant[];
  transactions: Transaction[];
  recurring: RecurringTransaction[];
  subscriptions: Subscription[];
  budgets: Budget[];
  goals: Goal[];
  loans: Loan[];
  investments: Investment[];
  debts: DebtRecord[];
} {
  const now = new Date();
  const currentYearMonth = now.toISOString().substring(0, 7); // e.g. "2026-08"
  const todayStr = now.toISOString().substring(0, 10);
  
  // Format dates helper
  const getDateOffset = (daysAgo: number): string => {
    const d = new Date();
    d.setDate(d.getDate() - daysAgo);
    return d.toISOString().substring(0, 10);
  };

  const accounts: Account[] = [
    {
      id: 'acc_hdfc_salary',
      name: 'HDFC Salary A/c',
      institution: 'HDFC Bank',
      type: 'SALARY',
      openingBalance: 145000,
      calculatedBalance: 145000,
      accountNumberLast4: '4589',
      icon: 'Landmark',
      color: '#004c8f',
      notes: 'Primary salary account',
      isActive: true,
      createdAt: Date.now() - 90 * 86400000,
      updatedAt: Date.now(),
    },
    {
      id: 'acc_icici_savings',
      name: 'ICICI Savings',
      institution: 'ICICI Bank',
      type: 'SAVINGS',
      openingBalance: 42500,
      calculatedBalance: 42500,
      accountNumberLast4: '9012',
      icon: 'PiggyBank',
      color: '#f58220',
      notes: 'Emergency fund reserve',
      isActive: true,
      createdAt: Date.now() - 120 * 86400000,
      updatedAt: Date.now(),
    },
    {
      id: 'acc_cash_wallet',
      name: 'Cash in Hand',
      institution: 'Cash',
      type: 'CASH',
      openingBalance: 6500,
      calculatedBalance: 6500,
      icon: 'Banknote',
      color: '#16A34A',
      notes: 'Physical pocket cash',
      isActive: true,
      createdAt: Date.now() - 180 * 86400000,
      updatedAt: Date.now(),
    },
    {
      id: 'acc_sbi_fd',
      name: 'SBI Fixed Deposit 3Yr',
      institution: 'State Bank of India',
      type: 'FIXED_DEPOSIT',
      openingBalance: 250000,
      calculatedBalance: 250000,
      accountNumberLast4: '7721',
      icon: 'Shield',
      color: '#280071',
      notes: '7.1% interest maturity in 2027',
      isActive: true,
      createdAt: Date.now() - 300 * 86400000,
      updatedAt: Date.now(),
    },
  ];

  const creditCards: CreditCard[] = [
    {
      id: 'cc_hdfc_regalia',
      name: 'HDFC Regalia Gold',
      issuer: 'HDFC Bank',
      network: 'VISA',
      cardTheme: 'gold',
      lastFourDigits: '8841',
      creditLimit: 300000,
      openingBalance: 0,
      currentOutstanding: 0,
      statementDate: 15,
      dueDate: 5,
      minimumDue: 1200,
      icon: 'CreditCard',
      color: '#d97706',
      notes: 'Lounge access & dining rewards',
      isActive: true,
      createdAt: Date.now() - 200 * 86400000,
      updatedAt: Date.now(),
    },
    {
      id: 'cc_icici_amazon',
      name: 'Amazon Pay ICICI',
      issuer: 'ICICI Bank',
      network: 'VISA',
      cardTheme: 'coral',
      lastFourDigits: '1904',
      creditLimit: 150000,
      openingBalance: 0,
      currentOutstanding: 0,
      statementDate: 20,
      dueDate: 10,
      minimumDue: 500,
      icon: 'CreditCard',
      color: '#f97316',
      notes: '5% unlimited Amazon cashback',
      isActive: true,
      createdAt: Date.now() - 150 * 86400000,
      updatedAt: Date.now(),
    },
    {
      id: 'cc_tata_neu',
      name: 'Tata Neu Infinity',
      issuer: 'HDFC Bank',
      network: 'RUPAY',
      cardTheme: 'amethyst',
      lastFourDigits: '5532',
      creditLimit: 250000,
      openingBalance: 0,
      currentOutstanding: 0,
      statementDate: 10,
      dueDate: 28,
      minimumDue: 750,
      icon: 'CreditCard',
      color: '#7c3aed',
      notes: '10% NeuCoins on Tata brand UPI spends',
      isActive: true,
      createdAt: Date.now() - 100 * 86400000,
      updatedAt: Date.now(),
    },
  ];

  const merchants: Merchant[] = [
    { id: 'm_swiggy', name: 'Swiggy', defaultCategoryId: 'food_dining', defaultPaymentAppId: 'gpay', defaultAccountId: 'acc_hdfc_salary', transactionCount: 14 },
    { id: 'm_blinkit', name: 'Blinkit', defaultCategoryId: 'groceries', defaultPaymentAppId: 'phonepe', defaultAccountId: 'acc_hdfc_salary', transactionCount: 18 },
    { id: 'm_uber', name: 'Uber India', defaultCategoryId: 'transport', defaultPaymentAppId: 'gpay', defaultAccountId: 'acc_hdfc_salary', transactionCount: 9 },
    { id: 'm_amazon', name: 'Amazon India', defaultCategoryId: 'shopping', defaultPaymentAppId: 'amazonpay', defaultAccountId: 'cc_icici_amazon', transactionCount: 11 },
    { id: 'm_bescom', name: 'Electricity (BESCOM)', defaultCategoryId: 'bills_utilities', defaultPaymentAppId: 'paytm', defaultAccountId: 'acc_hdfc_salary', transactionCount: 6 },
    { id: 'm_landlord', name: 'Sunil Kumar (Rent)', defaultCategoryId: 'home_rent', defaultPaymentAppId: 'gpay', defaultAccountId: 'acc_hdfc_salary', transactionCount: 8 },
  ];

  const subscriptions: Subscription[] = [
    {
      id: 'sub_netflix',
      name: 'Netflix Premium 4K',
      amount: 649,
      frequency: 'MONTHLY',
      nextBillingDate: getDateOffset(-12),
      categoryId: 'subscriptions',
      accountId: 'cc_hdfc_regalia',
      paymentAppId: 'cred',
      icon: 'Film',
      color: '#E50914',
      isActive: true,
    },
    {
      id: 'sub_spotify',
      name: 'Spotify Family Plan',
      amount: 179,
      frequency: 'MONTHLY',
      nextBillingDate: getDateOffset(-5),
      categoryId: 'subscriptions',
      accountId: 'acc_hdfc_salary',
      paymentAppId: 'gpay',
      icon: 'Music',
      color: '#1DB954',
      isActive: true,
    },
    {
      id: 'sub_wifi',
      name: 'Airtel Xstream Fiber 200Mbps',
      amount: 1179,
      frequency: 'MONTHLY',
      nextBillingDate: getDateOffset(-2),
      categoryId: 'bills_utilities',
      accountId: 'acc_hdfc_salary',
      paymentAppId: 'phonepe',
      icon: 'Wifi',
      color: '#E60000',
      isActive: true,
    },
    {
      id: 'sub_cultfit',
      name: 'Cult.fit Pass Annual',
      amount: 14999,
      frequency: 'YEARLY',
      nextBillingDate: '2027-01-15',
      categoryId: 'subscriptions',
      accountId: 'cc_hdfc_regalia',
      paymentAppId: 'cred',
      icon: 'Activity',
      color: '#FF3278',
      isActive: true,
    },
  ];

  const budgets: Budget[] = [
    {
      id: 'b_monthly_total',
      name: 'Total Monthly Budget',
      amount: 65000,
      month: currentYearMonth,
      rolloverType: 'NO_ROLLOVER',
      alertThresholdPercent: 80,
      color: '#3B82F6',
    },
    {
      id: 'b_food',
      name: 'Food & Dining',
      amount: 12000,
      categoryId: 'food_dining',
      month: currentYearMonth,
      rolloverType: 'NO_ROLLOVER',
      alertThresholdPercent: 85,
      color: '#EF4444',
    },
    {
      id: 'b_groceries',
      name: 'Groceries & Household',
      amount: 10000,
      categoryId: 'groceries',
      month: currentYearMonth,
      rolloverType: 'ROLLOVER_POSITIVE',
      alertThresholdPercent: 80,
      color: '#10B981',
    },
    {
      id: 'b_shopping',
      name: 'Shopping & Lifestyle',
      amount: 8000,
      categoryId: 'shopping',
      month: currentYearMonth,
      rolloverType: 'NO_ROLLOVER',
      alertThresholdPercent: 90,
      color: '#EC4899',
    },
  ];

  const loans: Loan[] = [
    {
      id: 'loan_sbi_car',
      name: 'SBI Car Loan (Tata Nexon)',
      type: 'VEHICLE',
      lenderName: 'State Bank of India',
      principalAmount: 600000,
      outstandingPrincipal: 385000,
      interestRateAnnual: 8.75,
      tenureMonths: 60,
      emiAmount: 12380,
      startDate: '2024-05-10',
      nextPaymentDate: getDateOffset(-10),
      linkedAccountId: 'acc_hdfc_salary',
      notes: 'Auto-debit on 10th of every month',
      createdAt: Date.now() - 450 * 86400000,
    },
  ];

  const investments: Investment[] = [
    {
      id: 'inv_nifty50',
      name: 'UTI Nifty 50 Index Fund Direct',
      category: 'MUTUAL_FUNDS',
      investedAmount: 180000,
      currentValue: 224500,
      purchaseDate: '2023-01-10',
      linkedAccountId: 'acc_hdfc_salary',
      notes: 'Monthly SIP of ₹10,000 on 5th',
      updatedAt: Date.now(),
    },
    {
      id: 'inv_parag_parikh',
      name: 'Parag Parikh Flexi Cap Fund',
      category: 'MUTUAL_FUNDS',
      investedAmount: 120000,
      currentValue: 162000,
      purchaseDate: '2023-06-15',
      linkedAccountId: 'acc_hdfc_salary',
      notes: 'International equity exposure',
      updatedAt: Date.now(),
    },
    {
      id: 'inv_sgb',
      name: 'Sovereign Gold Bonds (SGB 2023-24)',
      category: 'GOLD',
      investedAmount: 50000,
      currentValue: 68500,
      purchaseDate: '2023-11-20',
      notes: '2.5% semi-annual interest payout',
      updatedAt: Date.now(),
    },
    {
      id: 'inv_ppf',
      name: 'Public Provident Fund (PPF)',
      category: 'PPF',
      investedAmount: 150000,
      currentValue: 178000,
      purchaseDate: '2022-04-05',
      notes: 'Section 80C tax saving reserve',
      updatedAt: Date.now(),
    },
  ];

  const debts: DebtRecord[] = [
    {
      id: 'debt_rahul_trip',
      type: 'LENT',
      personName: 'Rahul Sharma',
      amount: 4500,
      remainingAmount: 4500,
      dueDate: getDateOffset(-15),
      notes: 'Goa weekend resort booking share',
      isSettled: false,
      createdAt: Date.now() - 10 * 86400000,
    },
    {
      id: 'debt_office_colleague',
      type: 'BORROWED',
      personName: 'Pooja (Colleague)',
      amount: 1200,
      remainingAmount: 0,
      notes: 'Lunch buffet split payment',
      isSettled: true,
      createdAt: Date.now() - 25 * 86400000,
    },
  ];

  const recurring: RecurringTransaction[] = [
    {
      id: 'rec_salary',
      name: 'Monthly Salary Credit',
      amount: 110000,
      type: 'INCOME',
      frequency: 'MONTHLY',
      startDate: '2024-01-01',
      nextDueDate: getDateOffset(-28),
      categoryId: 'salary',
      accountId: 'acc_hdfc_salary',
      merchantName: 'Tech Innovations Pvt Ltd',
      autoRecord: true,
      isActive: true,
    },
    {
      id: 'rec_sip',
      name: 'Nifty 50 Index SIP',
      amount: 10000,
      type: 'INVESTMENT_CONTRIBUTION',
      frequency: 'MONTHLY',
      startDate: '2024-01-05',
      nextDueDate: getDateOffset(-20),
      categoryId: 'misc_expense',
      accountId: 'acc_hdfc_salary',
      isActive: true,
    },
  ];

  const currentMonthDay = (day: number) => {
    const padDay = day < 10 ? `0${day}` : `${day}`;
    return `${currentYearMonth}-${padDay}`;
  };

  const transactions: Transaction[] = [
    // Current Month Transactions
    {
      id: 'tx_sal_current_month',
      amount: 110000,
      type: 'INCOME',
      date: currentMonthDay(1),
      time: '09:30',
      timestamp: new Date(`${currentYearMonth}-01T09:30:00`).getTime(),
      categoryId: 'salary',
      categoryName: 'Salary',
      merchantName: 'Tech Innovations Pvt Ltd',
      accountId: 'acc_hdfc_salary',
      accountName: 'HDFC Salary A/c',
      paymentAppId: 'netbanking',
      paymentAppName: 'Net Banking',
      notes: 'Monthly Net Salary credit',
      tags: ['#office'],
      createdAt: new Date(`${currentYearMonth}-01T09:30:00`).getTime(),
      updatedAt: new Date(`${currentYearMonth}-01T09:30:00`).getTime(),
    },
    {
      id: 'tx_freelance_income',
      amount: 15000,
      type: 'INCOME',
      date: currentMonthDay(3),
      time: '18:00',
      timestamp: new Date(`${currentYearMonth}-03T18:00:00`).getTime(),
      categoryId: 'salary',
      categoryName: 'Salary',
      merchantName: 'Upwork Global Client',
      accountId: 'acc_hdfc_salary',
      accountName: 'HDFC Salary A/c',
      paymentAppId: 'netbanking',
      paymentAppName: 'Net Banking',
      notes: 'UI/UX Consultation milestone payout',
      tags: ['#freelance'],
      createdAt: new Date(`${currentYearMonth}-03T18:00:00`).getTime(),
      updatedAt: new Date(`${currentYearMonth}-03T18:00:00`).getTime(),
    },
    {
      id: 'tx_rent',
      amount: 22000,
      type: 'EXPENSE',
      date: currentMonthDay(2),
      time: '11:00',
      timestamp: new Date(`${currentYearMonth}-02T11:00:00`).getTime(),
      categoryId: 'home_rent',
      categoryName: 'Home & Rent',
      subcategory: 'House Rent',
      merchantName: 'Sunil Kumar (Rent)',
      accountId: 'acc_hdfc_salary',
      accountName: 'HDFC Salary A/c',
      paymentAppId: 'gpay',
      paymentAppName: 'Google Pay',
      notes: 'Monthly 2BHK Apartment Rent',
      tags: ['#family'],
      createdAt: new Date(`${currentYearMonth}-02T11:00:00`).getTime(),
      updatedAt: new Date(`${currentYearMonth}-02T11:00:00`).getTime(),
    },
    {
      id: 'tx_car_emi',
      amount: 12380,
      type: 'LOAN_REPAYMENT',
      date: currentMonthDay(3),
      time: '10:00',
      timestamp: new Date(`${currentYearMonth}-03T10:00:00`).getTime(),
      categoryId: 'loans_emi',
      categoryName: 'Loans & EMI',
      loanId: 'loan_sbi_car',
      loanPrincipalPortion: 9580,
      loanInterestPortion: 2800,
      accountId: 'acc_hdfc_salary',
      accountName: 'HDFC Salary A/c',
      paymentAppId: 'netbanking',
      notes: 'SBI Car Loan EMI Auto-debit',
      createdAt: new Date(`${currentYearMonth}-03T10:00:00`).getTime(),
      updatedAt: new Date(`${currentYearMonth}-03T10:00:00`).getTime(),
    },
    {
      id: 'tx_sip_mf',
      amount: 10000,
      type: 'INVESTMENT_CONTRIBUTION',
      date: currentMonthDay(4),
      time: '08:00',
      timestamp: new Date(`${currentYearMonth}-04T08:00:00`).getTime(),
      categoryId: 'misc_expense',
      categoryName: 'Investments',
      investmentId: 'inv_nifty50',
      accountId: 'acc_hdfc_salary',
      accountName: 'HDFC Salary A/c',
      paymentAppId: 'netbanking',
      notes: 'UTI Nifty 50 SIP',
      createdAt: new Date(`${currentYearMonth}-04T08:00:00`).getTime(),
      updatedAt: new Date(`${currentYearMonth}-04T08:00:00`).getTime(),
    },
    {
      id: 'tx_atm_withdrawal',
      amount: 5000,
      type: 'TRANSFER',
      date: getDateOffset(4),
      time: '16:45',
      timestamp: Date.now() - 4 * 86400000,
      accountId: 'acc_hdfc_salary',
      accountName: 'HDFC Salary A/c',
      toAccountId: 'acc_cash_wallet',
      toAccountName: 'Cash in Hand',
      notes: 'ATM Cash Withdrawal for weekly pocket expenses',
      createdAt: Date.now() - 4 * 86400000,
      updatedAt: Date.now() - 4 * 86400000,
    },
    {
      id: 'tx_blinkit_groceries',
      amount: 1640,
      type: 'EXPENSE',
      date: getDateOffset(3),
      time: '19:20',
      timestamp: Date.now() - 3 * 86400000,
      categoryId: 'groceries',
      categoryName: 'Groceries',
      subcategory: 'Blinkit/Zepto/Instamart',
      merchantName: 'Blinkit',
      accountId: 'acc_hdfc_salary',
      accountName: 'HDFC Salary A/c',
      paymentAppId: 'phonepe',
      paymentAppName: 'PhonePe',
      notes: 'Milk, bread, fruits & essentials',
      createdAt: Date.now() - 3 * 86400000,
      updatedAt: Date.now() - 3 * 86400000,
    },
    {
      id: 'tx_swiggy_dinner',
      amount: 850,
      type: 'EXPENSE',
      date: getDateOffset(2),
      time: '20:45',
      timestamp: Date.now() - 2 * 86400000,
      categoryId: 'food_dining',
      categoryName: 'Food & Dining',
      subcategory: 'Swiggy/Zomato',
      merchantName: 'Swiggy',
      accountId: 'acc_hdfc_salary',
      accountName: 'HDFC Salary A/c',
      paymentAppId: 'gpay',
      paymentAppName: 'Google Pay',
      notes: 'Biryani combo + Gulab Jamun',
      createdAt: Date.now() - 2 * 86400000,
      updatedAt: Date.now() - 2 * 86400000,
    },
    {
      id: 'tx_amazon_shopping',
      amount: 3499,
      type: 'EXPENSE',
      date: getDateOffset(1),
      time: '14:15',
      timestamp: Date.now() - 1 * 86400000,
      categoryId: 'shopping',
      categoryName: 'Shopping',
      subcategory: 'Amazon/Flipkart',
      merchantName: 'Amazon India',
      creditCardId: 'cc_icici_amazon',
      creditCardName: 'Amazon Pay ICICI',
      paymentAppId: 'amazonpay',
      paymentAppName: 'Amazon Pay',
      notes: 'Ergonomic keyboard for home office',
      tags: ['#office'],
      createdAt: Date.now() - 1 * 86400000,
      updatedAt: Date.now() - 1 * 86400000,
    },
    {
      id: 'tx_uber_commute',
      amount: 420,
      type: 'EXPENSE',
      date: todayStr,
      time: '08:40',
      timestamp: Date.now() - 4 * 3600000,
      categoryId: 'transport',
      categoryName: 'Transport & Fuel',
      subcategory: 'Uber/Ola/Rapido',
      merchantName: 'Uber India',
      accountId: 'acc_hdfc_salary',
      accountName: 'HDFC Salary A/c',
      paymentAppId: 'gpay',
      paymentAppName: 'Google Pay',
      notes: 'Office ride in rain',
      tags: ['#office'],
      createdAt: Date.now() - 4 * 3600000,
      updatedAt: Date.now() - 4 * 3600000,
    },
    {
      id: 'tx_cash_tea',
      amount: 150,
      type: 'EXPENSE',
      date: todayStr,
      time: '11:15',
      timestamp: Date.now() - 2 * 3600000,
      categoryId: 'food_dining',
      categoryName: 'Food & Dining',
      subcategory: 'Cafes & Tea',
      merchantName: 'Chai Point Local',
      accountId: 'acc_cash_wallet',
      accountName: 'Cash in Hand',
      paymentAppId: 'cash_channel',
      paymentAppName: 'Cash in Hand',
      notes: 'Masala tea & samosas with team',
      createdAt: Date.now() - 2 * 3600000,
      updatedAt: Date.now() - 2 * 3600000,
    },
    // Previous Month Historical Transactions
    {
      id: 'tx_sal_prev_month',
      amount: 110000,
      type: 'INCOME',
      date: getDateOffset(28),
      time: '09:30',
      timestamp: Date.now() - 28 * 86400000,
      categoryId: 'salary',
      categoryName: 'Salary',
      merchantName: 'Tech Innovations Pvt Ltd',
      accountId: 'acc_hdfc_salary',
      accountName: 'HDFC Salary A/c',
      paymentAppId: 'netbanking',
      paymentAppName: 'Net Banking',
      notes: 'Previous month salary',
      createdAt: Date.now() - 28 * 86400000,
      updatedAt: Date.now() - 28 * 86400000,
    },
    {
      id: 'tx_rent_prev_month',
      amount: 22000,
      type: 'EXPENSE',
      date: getDateOffset(27),
      time: '11:00',
      timestamp: Date.now() - 27 * 86400000,
      categoryId: 'home_rent',
      categoryName: 'Home & Rent',
      merchantName: 'Sunil Kumar (Rent)',
      accountId: 'acc_hdfc_salary',
      accountName: 'HDFC Salary A/c',
      paymentAppId: 'gpay',
      notes: 'Previous month apartment rent',
      createdAt: Date.now() - 27 * 86400000,
      updatedAt: Date.now() - 27 * 86400000,
    },
    {
      id: 'tx_shopping_prev_month',
      amount: 5490,
      type: 'EXPENSE',
      date: getDateOffset(22),
      time: '16:20',
      timestamp: Date.now() - 22 * 86400000,
      categoryId: 'shopping',
      categoryName: 'Shopping',
      merchantName: 'Zara / H&M Mall',
      creditCardId: 'cc_icici_amazon',
      paymentAppId: 'cred',
      notes: 'Weekend apparel shopping',
      createdAt: Date.now() - 22 * 86400000,
      updatedAt: Date.now() - 22 * 86400000,
    },
  ];

  const goals: Goal[] = [
    {
      id: 'goal_emergency_fund',
      name: '6-Month Emergency Fund',
      targetAmount: 300000,
      currentAmount: 180000,
      targetDate: '2026-12-31',
      category: 'Savings & Safety',
      icon: 'Shield',
      color: '#10B981',
      linkedAccountId: 'acc_icici_savings',
      status: 'IN_PROGRESS',
      notes: '6 months of living expenses safely deposited in high-yield liquid account',
      allocations: [
        {
          id: 'alloc_1',
          amount: 100000,
          date: getDateOffset(60),
          type: 'DEPOSIT',
          notes: 'Initial seed deposit',
          accountId: 'acc_icici_savings',
          accountName: 'ICICI Savings',
          timestamp: Date.now() - 60 * 86400000,
        },
        {
          id: 'alloc_2',
          amount: 40000,
          date: getDateOffset(30),
          type: 'DEPOSIT',
          notes: 'July bonus allocation',
          accountId: 'acc_icici_savings',
          accountName: 'ICICI Savings',
          timestamp: Date.now() - 30 * 86400000,
        },
        {
          id: 'alloc_3',
          amount: 40000,
          date: getDateOffset(5),
          type: 'DEPOSIT',
          notes: 'August monthly savings',
          accountId: 'acc_icici_savings',
          accountName: 'ICICI Savings',
          timestamp: Date.now() - 5 * 86400000,
        },
      ],
      createdAt: Date.now() - 90 * 86400000,
      updatedAt: Date.now() - 5 * 86400000,
    },
    {
      id: 'goal_macbook_m4',
      name: 'MacBook Pro M4 (Space Black)',
      targetAmount: 199900,
      currentAmount: 145000,
      targetDate: '2026-10-15',
      category: 'Gadgets & Tech',
      icon: 'Laptop',
      color: '#6366F1',
      linkedAccountId: 'acc_hdfc_salary',
      status: 'IN_PROGRESS',
      notes: 'New workstation for coding and video production',
      allocations: [
        {
          id: 'alloc_mb_1',
          amount: 75000,
          date: getDateOffset(45),
          type: 'DEPOSIT',
          notes: 'Freelance project milestone 1',
          accountId: 'acc_hdfc_salary',
          accountName: 'HDFC Salary A/c',
          timestamp: Date.now() - 45 * 86400000,
        },
        {
          id: 'alloc_mb_2',
          amount: 70000,
          date: getDateOffset(15),
          type: 'DEPOSIT',
          notes: 'Freelance project milestone 2',
          accountId: 'acc_hdfc_salary',
          accountName: 'HDFC Salary A/c',
          timestamp: Date.now() - 15 * 86400000,
        },
      ],
      createdAt: Date.now() - 50 * 86400000,
      updatedAt: Date.now() - 15 * 86400000,
    },
    {
      id: 'goal_goa_trip',
      name: 'Goa Year-End Vacation',
      targetAmount: 50000,
      currentAmount: 50000,
      targetDate: '2026-11-20',
      category: 'Travel & Fun',
      icon: 'Palmtree',
      color: '#F59E0B',
      linkedAccountId: 'acc_cash_wallet',
      status: 'COMPLETED',
      notes: 'Flights + Villa booking with college friends (Goal fully funded!)',
      allocations: [
        {
          id: 'alloc_goa_1',
          amount: 25000,
          date: getDateOffset(40),
          type: 'DEPOSIT',
          notes: 'First installment',
          timestamp: Date.now() - 40 * 86400000,
        },
        {
          id: 'alloc_goa_2',
          amount: 25000,
          date: getDateOffset(10),
          type: 'DEPOSIT',
          notes: 'Final savings installment',
          timestamp: Date.now() - 10 * 86400000,
        },
      ],
      createdAt: Date.now() - 45 * 86400000,
      updatedAt: Date.now() - 10 * 86400000,
    },
  ];

  return {
    accounts,
    creditCards,
    merchants,
    transactions,
    recurring,
    subscriptions,
    budgets,
    goals,
    loans,
    investments,
    debts,
  };
}
